version: "3"
services:
  client:
    image: jaconsta/ships_battle_client:latest
    build: ./client
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - server
    volumes:
      - ./client/src/:/app/src/
  server:
    image: jaconsta/ships_battle_server:latest
    build: ./server
    ports:
      - "8080:8080"
    expose:
      - "3000"
    volumes:
      - ./server/src:/app/src/
